name: Build macOS Executable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clean environment
        run: |
          rm -rf venv/

      - name: Build executable
        env:
          ARCHFLAGS: "-arch x86_64 -arch arm64"  # 强制多架构编译
        run: |
          # 创建虚拟环境
          python -m venv venv
          source venv/bin/activate

          # 安装基础工具链
          pip install --upgrade pip setuptools wheel

          # 从源码安装关键依赖
          pip install pandas --no-binary pandas,numpy
          pip install selenium --no-binary selenium
          pip install -r requirements.txt --no-binary=:all:

          # 执行 PyInstaller（完整命令）
          pyinstaller \
            --onefile \
            --name myapp \
            --target-architecture=universal2 \
            --hidden-import=selenium \
            --hidden-import=platform \
            --hidden-import=certifi \
            --hidden-import=urllib3 \
            --hidden-import=sysconfig \
            --hidden-import=pkgutil \
            --hidden-import=uuid \
            --hidden-import=websocket \
            --hidden-import=xml.dom \
            --hidden-import=pandas \
            --hidden-import=pandas._libs.writers \
            --hidden-import=logging.handlers \
            --hidden-import=tkinter \
            --hidden-import=tkinter.filedialog \
            --collect-data=tkinter \
            --add-data "venv/lib/python3.11/site-packages/selenium:selenium" \
            --add-binary "venv/lib/python3.11/site-packages/selenium/webdriver/common/:selenium/webdriver/common" \
            --add-data "social_download:social_download" \
            --add-data "utils:utils" \
            --add-data "gui:gui" \
            --add-data "bidding_docx:bidding_docx" \
            --add-data "social_desensitize:social_desensitize" \
            --add-data "resources:resources" \
            --clean \
            --noconfirm \
            share_main.py

      - name: Verify binary
        run: |
          lipo -info dist/myapp  # 检查架构
          file dist/myapp        # 验证文件类型
