name: Build macOS Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          # 全局升级 pip（可选）
          python -m pip install --upgrade pip

      - name: Build macOS executable
        run: |
          # 创建并激活虚拟环境
          python -m venv venv
          source venv/bin/activate

          # 第一步：安装 PyInstaller 前强制卸载 pathlib
          pip uninstall -y pathlib || true

          # 安装 PyInstaller（固定版本）
          pip install pyinstaller==6.1.0

          # 第二步：安装项目依赖前再次卸载 pathlib
          pip uninstall -y pathlib || true

          # 安装项目依赖（忽略所有依赖的依赖）
          pip install --no-deps -r requirements.txt

          # 第三步：验证 pathlib 是否残留
          if pip list | grep pathlib; then
            echo "Error: pathlib 未完全卸载，终止构建！"
            exit 1
          fi

          # 构建命令
          pyinstaller --onefile --name myapp \
            --hidden-import logging.handlers \
            --hidden-import tkinter \
            --hidden-import tkinter.filedialog \
            --collect-data tkinter \
            --add-data "social_download:social_download" \
            --add-data "utils:utils" \
            --add-data "gui:gui" \
            --add-data "bidding_docx:bidding_docx" \
            --add-data "social_desensitize:social_desensitize" \
            --add-data "resources:resources" \
            share_main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/myapp
