name: Build macOS Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          # 升级 pip 到最新版本（可选，避免警告）
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install pyinstaller==6.1.0

          pip install -r requirements.txt

      - name: Build macOS executable
        run: |
          # 卸载全局 pathlib（仅在 macOS 环境需要）
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python -m pip uninstall pathlib -y

          # 创建虚拟环境
          python -m venv venv
          source venv/bin/activate
          
          # 在虚拟环境中强制卸载 pathlib
          pip uninstall -y pathlib || true  # 忽略卸载失败

          # 安装项目依赖（确保 requirements.txt 不含 pathlib）
          pip install -r requirements.txt

          # 再次检查 pathlib 是否残留（调试用）
          pip list | grep pathlib && exit 1 || echo "pathlib 已清理"
          
          pyinstaller --onefile --name myapp \
            --hidden-import social_download \
            --hidden-import utils \
            --hidden-import gui \
            --hidden-import bidding_docx \
            --hidden-import social_desensitize \
            --add-data "social_download:social_download" \
            --add-data "utils:utils" \
            --add-data "gui:gui" \
            --add-data "bidding_docx:bidding_docx" \
            --add-data "social_desensitize:social_desensitize" \
            --add-data "resources:resources" \
            share_main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/myapp
